### ISSUE TITLE
大佬,接口调用不通了

### ISSUE THREAD

**Issue by Clarence-yp** [mercyxu/KLine#1]
大佬,  参考你的demo在写项目 然后早上发现接口调用不通了,能更新下 或者 用本地假数据不, 谢谢

**Comment by mercyxu** [comment]
不好意思,因为数据是用的我司测试服数据,因为某些原因停用了,可以耐心等待恢复或者使用你们自己后台的数据,替换接口就可以了

**Comment by mercyxu** [comment]
已恢复
