### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by chelin192837** [mercyxu/KLine#2]
你好,你的接口调不通了,今天才这样的

**Comment by mercyxu** [comment]
不好意思,因为数据是用的我司测试服数据,因为某些原因停用了,可以耐心等待恢复或者使用你们自己后台的数据,替换接口就可以了

**Comment by chelin192837** [comment]
你好,首先真的非常感谢你,你的代码真的写的很好,我真想好好学习,不介意的话,我想问一下你们公司什么开启服务啊,如果用我们公司的数据的话,字段的格式我们不太清楚,所以很麻烦的

在 2019-08-06 18:57:17，"mercyxu" <notifications@github.com> 写道：


不好意思,因为数据是用的我司测试服数据,因为某些原因停用了,可以耐心等待恢复或者使用你们自己后台的数据,替换接口就可以了

**Comment by mercyxu** [comment]
已恢复正常

**Comment by chelin192837** [comment]
谢谢,万分感谢🙏🙏🙏🙏🙏🙏

在 2019-08-06 23:55:36，"mercyxu" <notifications@github.com> 写道：


Closed #2.
